
[global]
    history = 3600
    dbengine multihost disk space = 256
    debug log = error
    error log = notice
    info log = default
    memory mode = dbengine
    update every = 5
    flip uptime on reboot = auto
    cleanup obsolete charts after = 3600

[directories]
    config  = /usr/local/etc/netdata
    log     = /usr/local/var/log/netdata
    lib     = /usr/local/var/lib/netdata
    cache   = /usr/local/var/cache/netdata
    plugins = /usr/local/usr/libexec/netdata/plugins.d
    stock config = /usr/local/usr/lib/netdata/conf.d
    stock data   = /usr/local/usr/share/netdata
    web          = /usr/local/usr/share/netdata/web

[plugins]
    go.d = no
    proc = yes
    apps = yes
    cgroups = yes
    ebpf = yes
    network-viewer = yes
    systemd-journal = no
    tc = no
    idlejitter = no
    nfacct = no
    xenstat = no
    perf = no
    slabinfo = no
    freeipmi = no
    cups = no

[python.d]
    update every = 15

    model directory = /var/cache/ml
    anomaly detection min. metrics = 20
    anomaly detection min. time = 900
    anomaly detection max. time = 604800

[backend]
    enabled = no

[health]
    enabled = yes
    frequency = 60
    log health changes = yes
    health check command options = -maxlines 100

[charts.d]
    update every = 5

[logging]
    error = /usr/local/var/log/netdata/error.log
    access = /usr/local/var/log/netdata/access.log

[web]
    bind to = *

[plugins.d]
    proc = yes
    tc = no
